name: Delete Old

on:
  schedule:
    - cron: "*/18 0-15 * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-workflow-runs@main
        id: delete-workflow-runs
        with:
          repository: llxlr/llxlr
          older-than-seconds: 86400
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
